### PR TITLE
fix issue 161

### PR DESCRIPTION
**Pull request by Edward67**

### CODE REVIEW

**Comment by WickyNilliams** [comment]
Thanks!

This requires a few changes in order to be merged:

1. Build is failing due to broken test. Could you fix this please?
2. Changes should be made only files in `src`. I will handle building `dist` files and bumping version in package.json

**Comment by Edward67** [comment]
Learned, thank you very much

**Comment by WickyNilliams** [comment]
But now you have deleted the (contents of the) `dist` files :) Maybe easier to open a new PR, with just changes to `src`?

**Comment by WickyNilliams** [comment]
Also, here's a top tip. If you title the PR or a commit message "fix #161" (with the hash before the number), github will automatically close the issue when merged :) See here for more info https://help.github.com/articles/closing-issues-via-commit-messages/

**Pull request closed without merging**
