### PR TITLE
Added Meteor Support

### PR DESCRIPTION
**Pull request by patrickleet**
Had to change up readme.md a bit because Meteor parses it, and the formatting that it was in complained.
Added grunt tasks for running meteor tests (basically that it loads, as enquires tests handle the real testing) and for releasing a new version to atmosphere.meteor.com

I pointed the meteor package.js config at my fork's url for now, but you should probably make it yours when you pull it if you want to release it officially on meteor's package system. Up to you. If you release it you'll want to change the name as well wickynilliams:enquire. You'll have to create a meteor account to do so.

### CODE REVIEW

**Comment by patrickleet** [comment]
Can I do anything to help this get pulled? 

It doesn't touch any of the enquire.js lib at all. I also added grunt tasks for dealing with all meteor related tasks.

**Comment by WickyNilliams** [comment]
I don't want to add a load of things to the repo for meteor's benefit. Surely this is not the requirement to be supported by meteor? I will fix up the README, because that is a sensible change, but I'm opposed to the other changes.

I'll close this and make the README changes myself. Excuse the delay, thanks anyway

**Comment by fourpixels** [comment]
Wow, two years later! :) It's best to donate the project to someone that has a bit more time to handle all those messy stuff around. Anyways, it was a great job that you did!

**Comment by WickyNilliams** [comment]
Haha yeah I have neglected this project quite badly. I'm trying to clean everything up now, and then I'm going to see if I can find some maintainers to help out

**Pull request closed without merging**
